### ISSUE TITLE
没办法正常签到，试了三个签到了

### ISSUE THREAD

**Issue by kamabokowen** [yuban10703/chaoxingsign#14]
看运行日志的话，登录和获取课程信息是正常的，但是当签到的时候就出现问题了。

`2020-04-22 01:56:13 [签到] 智能仪器原理及应用 查询到待签到活动 活动名称:4.22 活动状态: 活动时间: aid:2******5

Starting new HTTPS connection (1): mobilelearn.chaoxing.com:443

https://mobilelearn.chaoxing.com:443 "POST /pptSign/stuSignajax HTTP/1.1" 500 539

签到状态: <!DOCTYPE html>

<html>

<head>

<title>Error</title>

<style>

    body {

        width: 35em;

        margin: 0 auto;

        font-family: Tahoma, Verdana, Arial, sans-serif;

    }

</style>

</head>

<body>

<h1>An error occurred.</h1>

<p>Sorry, the page you are looking for is currently unavailable.<br/>

Please try again later.</p>

<p>If you are the system administrator of this resource then you should check

the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>

<p><em>Faithfully yours, tengine.</em></p>

</body>

</html>`

**Comment by yuban10703** [comment]
emmmm

**Comment by yuban10703** [comment]
你是用的云函数么?

**Comment by kamabokowen** [comment]
对不起，打扰了，我无脑套用代码出的问题。
读了代码之后发现您的那个“偷懒”实现方法
所以必须写经纬度。现在正常了，谢谢您。
