### ISSUE TITLE
请教一下多用户怎么添加 

### ISSUE THREAD

**Issue by 182919** [yuban10703/chaoxingsign#17]
请教作者多用户怎么添加 。并且配置文件里除了账户和密码那些是必填项

**Comment by yuban10703** [comment]
![image](https://user-images.githubusercontent.com/39484884/81326246-21062380-90cc-11ea-88e4-5ed80602ebf2.png)

**Comment by yuban10703** [comment]
里面每一项都有一个默认的空值

**Comment by yuban10703** [comment]
只有账号密码是必填的

**Comment by 182919** [comment]
我太爱你的回复速度了 谢谢你
