### ISSUE TITLE
云函数错误提示

### ISSUE THREAD

**Issue by sodading** [yuban10703/chaoxingsign#18]
返回结果
Traceback (most recent call last):

  File "/var/user/index.py", line 225, in main_handler

    CxSign.subject(m)

  File "/var/user/index.py", line 72, in subject

    cdata = json.loads(res.text)

  File "/var/lang/python3/lib/python3.6/json/__init__.py", line 354, in loads

    return _default_decoder.decode(s)

  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 357, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by sodading** [comment]
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 251, in main_handler\n    CxSign.taskactivelist(o)\n  File \"/var/user/index.py\", line 125, in taskactivelist\n    CxSign.sign(aid, i, index)  # 调用签到函数\n  File \"/var/user/index.py\", line 160, in sign\n    CxSign.upload(i)\n  File \"/var/user/index.py\", line 145, in upload\n    files = {'file': (picname, open(picname, 'rb'),\nFileNotFoundError: [Errno 2] No such file or directory: 'test.png'"}

**Comment by sodading** [comment]
新版本运行日志（测试失败）

START RequestId: 03ae3747-54a9-4871-aa4c-e2778b1f42a9

Event RequestId: 03ae3747-54a9-4871-aa4c-e2778b1f42a9

Starting new HTTPS connection (1): passport2-api.chaoxing.com:443

https://passport2-api.chaoxing.com:443 "POST /v11/loginregister HTTP/1.1" 200 108

用户: 0 获取cookie成功

Starting new HTTP connection (1): mooc1-api.chaoxing.com:80

http://mooc1-api.chaoxing.com:80 "GET /mycourse/backclazzdata HTTP/1.1" 200 None

2020-05-11 01:29:33 用户: 0 正在查询课程: 新冠期间

Starting new HTTPS connection (1): mobilelearn.chaoxing.com:443

https://mobilelearn.chaoxing.com:443 "GET /ppt/activeAPI/taskactivelist?courseId=211886238&classId=26868400&uid=89512335 HTTP/1.1" 200 None

2020-05-11 01:29:35 用户: 0 正在查询课程: 会计

Starting new HTTPS connection (1): mobilelearn.chaoxing.com:443

https://mobilelearn.chaoxing.com:443 "GET /ppt/activeAPI/taskactivelist?courseId=211920996&classId=25797498&uid=89512335 HTTP/1.1" 200 None

2020-05-11 01:29:35 [签到] 会计 查询到待签到活动 活动名称:签到 活动状态: 活动时间: aid:233242825
 

ERROR RequestId:03ae3747-54a9-4871-aa4c-e2778b1f42a9 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 251, in main_handler\n    CxSign.taskactivelist(o)\n  File \"/var/user/index.py\", line 125, in taskactivelist\n    CxSign.sign(aid, i, index)  # 调用签到函数\n  File \"/var/user/index.py\", line 160, in sign\n    CxSign.upload(i)\n  File \"/var/user/index.py\", line 145, in upload\n    files = {'file': (picname, open(picname, 'rb'),\nFileNotFoundError: [Errno 2] No such file or directory: 'test.png'"} 

END RequestId: 03ae3747-54a9-4871-aa4c-e2778b1f42a9

Report RequestId: 03ae3747-54a9-4871-aa4c-e2778b1f42a9 Duration:4940ms Memory:64MB MemUsage:19.906250MB

**Comment by yuban10703** [comment]
你云函数的地区不会在广州吧？...

**Comment by sodading** [comment]
成都  多少有点毛病 刚才测试通过了

**Comment by yuban10703** [comment]
> 成都  多少有点毛病 刚才测试通过了

那就好~..
