### ISSUE TITLE
新版本测试通过后调用失败

### ISSUE THREAD

**Issue by sodading** [yuban10703/chaoxingsign#19]
成都的 会有哪些原因导致失败呢？
返回数据:
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 247, in main_handler\n    CxSign.subject(m)\n  File \"/var/user/index.py\", line 75, in subject\n    cdata = json.loads(res.text)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"}
日志:
START RequestId: 448dec87-b5c2-4806-96d6-fb3f5dbd977f
Event RequestId: 448dec87-b5c2-4806-96d6-fb3f5dbd977f
Starting new HTTPS connection (1): passport2-api.chaoxing.com:443
https://passport2-api.chaoxing.com:443 "POST /v11/loginregister HTTP/1.1" 200 108
用户: 0 获取cookie成功
Starting new HTTP connection (1): mooc1-api.chaoxing.com:80
http://mooc1-api.chaoxing.com:80 "GET /mycourse/backclazzdata HTTP/1.1" 403 None
ERROR RequestId:448dec87-b5c2-4806-96d6-fb3f5dbd977f Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 247, in main_handler\n    CxSign.subject(m)\n  File \"/var/user/index.py\", line 75, in subject\n    cdata = json.loads(res.text)\n  File \"/var/lang/python3/lib/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lang/python3/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"} 

END RequestId: 448dec87-b5c2-4806-96d6-fb3f5dbd977f

Report RequestId: 448dec87-b5c2-4806-96d6-fb3f5dbd977f Duration:881ms Memory:64MB MemUsage:20.035156MB

**Comment by yuban10703** [comment]
你把地区换到香港试试。。

**Comment by sodading** [comment]
! 切换完稳定下来

**Comment by sodading** [comment]
这玩意能笔画签到？

**Comment by yuban10703** [comment]
> 这玩意能笔画签到？

笔画签到是什么？。。。

**Comment by sodading** [comment]
类似安卓手机图案解锁

**Comment by yuban10703** [comment]
> 类似安卓手机图案解锁

可以的。。
