### ISSUE TITLE
签到报错

### ISSUE THREAD

**Issue by BeginnerStars** [yuban10703/chaoxingsign#6]
<!DOCTYPE html>
<html>
<head>
<title>Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>Sorry, the page you are looking for is currently unavailable.<br/>
Please try again later.</p>
<p>If you are the system administrator of this resource then you should check
the <a href="http://nginx.org/r/error_log">error log</a> for details.</p>
<p><em>Faithfully yours, tengine.</em></p>
</body>
</html>

**Comment by yuban10703** [comment]
有报错的截图么.......或者日志...

**Comment by BeginnerStars** [comment]
目前只有一张server的通知，窗口刚刚不小心关闭了。没截图到





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuban10703"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 上午10:43
收件人:&nbsp;"yuban10703/chaoxingsign"<chaoxingsign@noreply.github.com&gt;;
抄送:&nbsp;"绫度科技"<1648805191@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuban10703/chaoxingsign] 签到报错 (#6)





 
有报错的截图么.......或者日志...

**Comment by yuban10703** [comment]
你用的是哪个文件?
是server酱的推送报的错么?
emmm....

**Comment by BeginnerStars** [comment]
chaoxingsign.py&nbsp;
运行报错内容我提交在Github了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuban10703"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 上午10:50
收件人:&nbsp;"yuban10703/chaoxingsign"<chaoxingsign@noreply.github.com&gt;;
抄送:&nbsp;"绫度科技"<1648805191@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuban10703/chaoxingsign] 签到报错 (#6)





 
你用的是哪个文件?
 是server酱的推送报的错么?
 emmm....

**Comment by yuban10703** [comment]
emm
哪个是报错内容?........

**Comment by BeginnerStars** [comment]
报错内容在GitHub，截图是server酱的返回数据





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuban10703"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 中午11:22
收件人:&nbsp;"yuban10703/chaoxingsign"<chaoxingsign@noreply.github.com&gt;;
抄送:&nbsp;"绫度科技"<1648805191@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuban10703/chaoxingsign] 签到报错 (#6)





 
emm
 哪个是报错内容?........

**Comment by yuban10703** [comment]
![J}7K@( U}UE770~WJB@A4{V](https://user-images.githubusercontent.com/39484884/78627007-f9504f80-78c2-11ea-8cf8-a69375cf8a23.png)
emmm........

**Comment by BeginnerStars** [comment]
好了，麻烦现在看一下。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuban10703"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 中午11:29
收件人:&nbsp;"yuban10703/chaoxingsign"<chaoxingsign@noreply.github.com&gt;;
抄送:&nbsp;"绫度科技"<1648805191@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuban10703/chaoxingsign] 签到报错 (#6)





 

 emmm........

**Comment by yuban10703** [comment]
啊?...好像没什么变化呀......
![OFX DMNMC0NWATBVF%10KS5](https://user-images.githubusercontent.com/39484884/78631750-b5b01280-78cf-11ea-93bc-fed62e7868fa.png)
