### ISSUE TITLE
唔……炸了呢

### ISSUE THREAD

**Issue by tjc0726** [yuban10703/chaoxingsign#7]
发现云函数有时候那个index不会初始化成0而是接着上一次执行后的index继续……应该是腾讯云的bug⑧ 日志里有些多出来的数字就是为了debug这个用哒 请忽略

**然后到了要签到的那门课就会出现以下的报错**

返回数据:
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 400, in main_handler\n    sign.doSign()\n  File \"/var/user/index.py\", line 367, in doSign\n    CxSign.coursedata[i]['classid'])\n  File \"/var/user/index.py\", line 194, in taskactivelist\n    aid = CxSign.getvar(signurl)\nTypeError: getvar() missing 1 required positional argument: 'url'"}

日志:
START RequestId: a0d10ce8-49c7-4e46-aa3d-f6e7754fdeb4
Event RequestId: a0d10ce8-49c7-4e46-aa3d-f6e7754fdeb4
Starting new HTTPS connection (1): passport2-api.chaoxing.com:443
https://passport2-api.chaoxing.com:443 "POST /v11/loginregister HTTP/1.1" 200 108
Starting new HTTP connection (1): mooc1-api.chaoxing.com:80
http://mooc1-api.chaoxing.com:80 "GET /mycourse/backclazzdata?view=json&rss=1 HTTP/1.1" 200 None
获取成功:
0.课程名称:大学物理实验(3)
1.课程名称:材料力学(2)
2.课程名称:微积分(3)
3.课程名称:疲劳与断裂
4.课程名称:化工与健康
5.课程名称:市场经济与政府职能
6.课程名称:游泳(3)
7.课程名称:科学与工程中的计算方法
8.课程名称:人工智能
9.课程名称:形势与政策
10.课程名称:法律的伦理困境
11.课程名称:振动力学
12.课程名称:关爱健康，关爱社会
13.课程名称:大学物理(2)
14.课程名称:毛泽东思想和中国特色社会主义理论体系概论B(2)
15.课程名称:思想道德修养与法律基础A
16.课程名称:理论力学(2)
17.课程名称:中国近现代史纲要B
18.课程名称:形势与政策
19.课程名称:大学物理(1)
20.课程名称:工程热力学概论
21.课程名称:数学物理方法(2)
22.课程名称:马克思主义基本原理概论B
23.课程名称:英语中级阅读
24.课程名称:大学英语B级(2)
25.课程名称:大学物理(3)
26.课程名称:人机交互初探
27.课程名称:选修课-大学生安全教育
28.课程名称:必修课-大学生安全教育
29.课程名称:大学化学
30.课程名称:网络通信的奥秘
31.课程名称:大学物理实验(3)
32.课程名称:材料力学(2)
33.课程名称:微积分(3)
34.课程名称:疲劳与断裂
35.课程名称:化工与健康
36.课程名称:市场经济与政府职能
37.课程名称:游泳(3)
38.课程名称:科学与工程中的计算方法
39.课程名称:人工智能
40.课程名称:形势与政策
41.课程名称:法律的伦理困境
42.课程名称:振动力学
43.课程名称:关爱健康，关爱社会
44.课程名称:大学物理(2)
45.课程名称:毛泽东思想和中国特色社会主义理论体系概论B(2)
46.课程名称:思想道德修养与法律基础A
47.课程名称:理论力学(2)
48.课程名称:中国近现代史纲要B
49.课程名称:形势与政策
50.课程名称:大学物理(1)
51.课程名称:工程热力学概论
52.课程名称:数学物理方法(2)
53.课程名称:马克思主义基本原理概论B
54.课程名称:英语中级阅读
55.课程名称:大学英语B级(2)
56.课程名称:大学物理(3)
57.课程名称:人机交互初探
58.课程名称:选修课-大学生安全教育
59.课程名称:必修课-大学生安全教育
60.课程名称:大学化学
61.课程名称:网络通信的奥秘
62
运行于云函数模式
0
Starting new HTTPS connection (1): mobilelearn.chaoxing.com:443
https://mobilelearn.chaoxing.com:443 "GET /ppt/activeAPI/taskactivelist?courseId=211534600&classId=24532761&uid=79142029 HTTP/1.1" 200 None
2020-04-08 10:08:05 [监控运行中]课程: 大学物理实验(3) 未查询到签到活动
1
Starting new HTTPS connection (1): mobilelearn.chaoxing.com:443
https://mobilelearn.chaoxing.com:443 "GET /ppt/activeAPI/taskactivelist?courseId=211462846&classId=24295477&uid=79142029 HTTP/1.1" 200 None
2020-04-08 10:08:05 [监控运行中]课程: 材料力学(2) 未查询到签到活动
2
Starting new HTTPS connection (1): mobilelearn.chaoxing.com:443
https://mobilelearn.chaoxing.com:443 "GET /ppt/activeAPI/taskactivelist?courseId=211418582&classId=24146570&uid=79142029 HTTP/1.1" 200 None
2020-04-08 10:08:05 [监控运行中]课程: 微积分(3) 未查询到签到活动
3
Starting new HTTPS connection (1): mobilelearn.chaoxing.com:443
https://mobilelearn.chaoxing.com:443 "GET /ppt/activeAPI/taskactivelist?courseId=211415731&classId=24136276&uid=79142029 HTTP/1.1" 200 None
 
ERROR RequestId:a0d10ce8-49c7-4e46-aa3d-f6e7754fdeb4 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 400, in main_handler\n    sign.doSign()\n  File \"/var/user/index.py\", line 367, in doSign\n    CxSign.coursedata[i]['classid'])\n  File \"/var/user/index.py\", line 194, in taskactivelist\n    aid = CxSign.getvar(signurl)\nTypeError: getvar() missing 1 required positional argument: 'url'"} 
END RequestId: a0d10ce8-49c7-4e46-aa3d-f6e7754fdeb4
Report RequestId: a0d10ce8-49c7-4e46-aa3d-f6e7754fdeb4 Duration:871ms Memory:64MB MemUsage:19.976562MB

**Comment by yuban10703** [comment]
这么多课啊.......

**Comment by tjc0726** [comment]
> 这么多课啊.......

害 有好多些都是上完的 但是好像全被扫描出来了呢

**Comment by yuban10703** [comment]
好像是有点问题,我晚点看看.....,可以先用普通版....

**Comment by tjc0726** [comment]
> 好像是有点问题,我晚点看看.....,可以先用普通版....

ooooooooook
