### ISSUE TITLE
普通版签到报错

### ISSUE THREAD

**Issue by BeginnerStars** [yuban10703/chaoxingsign#8]
还是上次那个问题
报错截图https://image.lingdukeji.top/imgs/2020/04/72f95b9f4f38f9cb.png
麻烦看一下，上次qq邮箱回复，附件无法传到GitHub

**Comment by yuban10703** [comment]
emmmm,从来没遇到过,能说一下运行环境么.....py版本什么的?.....

**Comment by BeginnerStars** [comment]
windouws10 python3.7





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuban10703"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 上午10:26
收件人:&nbsp;"yuban10703/chaoxingsign"<chaoxingsign@noreply.github.com&gt;;
抄送:&nbsp;"帝九梦_frank_test"<1648805191@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuban10703/chaoxingsign] 普通版签到报错 (#8)





 
emmmm,从来没遇到过,能说一下运行环境么.....py版本什么的?.....

**Comment by yuban10703** [comment]
你试试更新下python的模块试试,不清楚哪里有问题........再不行就试试云函数吧,,,,,,,,,

**Comment by BeginnerStars** [comment]
好的好的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yuban10703"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月9日(星期四) 上午10:31
收件人:&nbsp;"yuban10703/chaoxingsign"<chaoxingsign@noreply.github.com&gt;;
抄送:&nbsp;"帝九梦_frank_test"<1648805191@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yuban10703/chaoxingsign] 普通版签到报错 (#8)





 
你试试更新下python的模块试试,不清楚哪里有问题........再不行就试试云函数吧,,,,,,,,,
